### ISSUE TITLE
PHP8 count() error in imagebrowser.php:221

### ISSUE THREAD

**Issue by igestalten** [GetSimpleCMS-CE-plugins/plugin-i18n-Gallery#1]
Getting error when trying to upload new images to gallery (PHP 8.0):

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /path/plugins/i18n_gallery/browser/imagebrowser.php:221 
Stack trace: #0 {main} thrown in /path/plugins/i18n_gallery/browser/imagebrowser.php on line 221 

should be fixed with is_countable() ?

**Comment by risingisland** [comment]
Slightly late reply.
I am guessing that the 2.3.0 update fixed this.
